[env:esp32s3usbotg]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 9600

board_upload.flash_size = 16MB
board_build.arduino.memory_type = qio_opi 
board_build.partitions = default_16MB.csv
board_build.filesystem = littlefs

build_unflags =
  -DARDUINO_USB_MODE=1

build_flags = 
    -I include
    -D CORE_DEBUG_LEVEL=1
    -D BOARD_HAS_PSRAM
	-UARDUINO_USB_MODE
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0
		
lib_deps = 
	links2004/WebSockets@^2.7.3
	adafruit/Adafruit MPU6050@^2.2.9
	hideakitai/MPU9250@^0.4.8
	adafruit/Adafruit GFX Library@^1.12.6
	adafruit/Adafruit SSD1306@^2.5.16
	bblanchon/ArduinoJson @ ^7.0.4
